Added eitr and health attack usage
Grantapher/ValheimPlus pull request #66
Opened 2024-05-22 14:58 UTC by Bellian

Hello, Just got everything working and try to help out!

This pach adds eitr and health usage config to magic items.

2024-05-24 01:15 UTC, Grantapher requested changes
Thanks for adding this!

Have a few nits on how the code looks, but after that it is all good. 

I can also make the changes in a follow up commit if you would prefer that, just comment below on this PR.

2024-05-24 01:15 UTC, Grantapher commented on ValheimPlus/GameClasses/Attack.cs
> +    [HarmonyPatch(typeof(Attack), "GetAttackEitr")]
replace the string literal with:

```csharp
nameof(Attack.GetAttackEitr)
```

2024-05-24 01:15 UTC, Grantapher commented on ValheimPlus/GameClasses/Attack.cs
> +                        skillType = Skills.SkillType.Unarmed;
Looks like this is pointless to compute since the switch later doesn't include it. Seems like we can just early return in item is null.

2024-05-24 01:15 UTC, Grantapher commented on ValheimPlus/GameClasses/Attack.cs
> +    }
This method and the previous are pretty close to the same, so the comments on the previous should also be applied to this one.

2024-05-24 07:52 UTC, Bellian commented on ValheimPlus/GameClasses/Attack.cs
> +                {
Jea just copy pasted from the StaminaUsage stuff. Can do.

2024-05-24 07:57 UTC, Bellian commented on ValheimPlus/GameClasses/Attack.cs
> +    [HarmonyPatch(typeof(Attack), "GetAttackEitr")]
will fix all of them.

2024-05-24 08:04 UTC, Bellian commented on ValheimPlus/GameClasses/Attack.cs
> +                        skillType = Skills.SkillType.Unarmed;
Jea just a copy of the stamina. stuff.
Do not think they will later add health or eitr costs to unarmed attacks eigther.

2024-05-24 08:06 UTC, Bellian commented
ping @Grantapher

2024-05-25 00:27 UTC, Grantapher approved these changes
Thanks for the updates! If I realized it was just a stamina copy/paste I would have fixed them myself. Whoops.

2024-05-25 00:28 UTC, merged