Oven pr
Grantapher/ValheimPlus pull request #72
Opened 2024-05-24 18:59 UTC by snorkyware

2024-05-25 06:57 UTC, Grantapher requested changes
Just one main comment.

Also, when this is force-pushed, can you squash the commits?

2024-05-25 06:57 UTC, Grantapher commented on ValheimPlus/GameClasses/CookingStation.cs
> +                !Configuration.Current.Oven.infiniteFuel;
I'm not allowing method skipping unless it is absolutely necessary. This should be able to be done without method skipping, can you update it to do so?

2024-05-27 19:17 UTC, snorkyware commented on ValheimPlus/GameClasses/CookingStation.cs
> +                !Configuration.Current.Oven.infiniteFuel;
Okay, this is good advice. I'll have a look if I get time. Please feel free to make whatever changes you see fit in the mean time.

2024-05-29 07:00 UTC, closed without merging

2024-05-29 07:00 UTC, Grantapher commented
Committed in 0978253.