Added auto "stack all" to all chests in range
Grantapher/ValheimPlus pull request #75
Opened 2024-05-25 13:01 UTC by Bellian

This feature will perform the "Stack all" function on all chests in range.
This will automaticaly sort all items from the player inventory into chests in range.

Works with the "stack all" button in inventory as well as holding the "E" button.

Also adds a feature to disable equipment to be placed in chests using the "Stack all" feature.
So you keep your hammer in inventory if another hammer is inside of a chest.

2024-05-25 13:08 UTC, Bellian commented
Don't know for sure how to test this for multiplayer.
Any advice here @Grantapher?

2024-05-25 18:14 UTC, Grantapher commented
I believe you can open the game multiple times on the same computer, but you will need to set up a dedicated server as well (which can also likely be done on the same computer).

2024-05-26 00:03 UTC, Bellian commented
Nope, just got me banned from this server XD
Will test tomorrow with someone else.

2024-05-26 12:17 UTC, Bellian commented
Works in multiplayer. Will also prevent auto sorting in chests if they are opened by anyone else. Guess this is intended since inventories are exclusively blocked if opened to prevent sideeffects.

But it will show a message. Should i see if i can remove this message?

2024-05-27 02:12 UTC, Grantapher requested changes

2024-05-27 02:12 UTC, Grantapher commented on ValheimPlus/GameClasses/Inventory.cs
> +            catch (Exception) { }
Why swallow any exception? We should find out why there are any instead of stopping once we receive one.

2024-05-27 02:12 UTC, Grantapher commented on ValheimPlus/GameClasses/Inventory.cs
> +        static void Prefix(Inventory __instance, ref bool message)
Prefix should probably go before Postfix.

2024-05-27 02:12 UTC, Grantapher commented on ValheimPlus/GameClasses/Inventory.cs
> +                AutoStackAllStore.currentInventory = __instance;
Seems like `AutoStackAllStore.currentInventory != null` is probably sufficient for replacing `AutoStackAllStore.isStacking`.

2024-05-27 02:12 UTC, Grantapher commented on ValheimPlus/GameClasses/Inventory.cs
> +            if (!AutoStackAllStore.isStacking || !Configuration.Current.Inventory.autoStackAll || !Configuration.Current.Inventory.autoStackAllIgnoreEquipment) return;
probably should also use a `__instance != AutoStackAllStore.currentInventory` check

2024-05-27 02:12 UTC, Grantapher commented on ValheimPlus/GameClasses/Inventory.cs
> +            // ony perform during auto stacking!
Is this only during the `StackAll` method? If so, it may make more sense to just transpile out that method in the `StackAll` rather than have this static boolean around.

2024-05-27 07:06 UTC, Bellian commented on ValheimPlus/GameClasses/Inventory.cs
> +            catch (Exception) { }
Just had that in case it triggers if chests are blocked. But it does not ^^'

2024-05-27 07:16 UTC, Bellian commented on ValheimPlus/GameClasses/Inventory.cs
> +            // ony perform during auto stacking!
I can not follow.
The ContainsItemByName Mathod should only be bypassed if we are stacking all items.
This method might also affect checking your inventory for items you need for crafting. So i can not just remove it.

Or do you mean I should in the StackAll Prefix method override the method and later restore it?
Have not yet into this transpiling shenanigans.

2024-05-27 10:21 UTC, Bellian commented on ValheimPlus/GameClasses/Inventory.cs
> +            // ony perform during auto stacking!
Ok convertes in a transpile if the feature is active. Works fine and learned alot.
Thanks for the heads up.

2024-05-27 18:53 UTC, Grantapher requested changes
Code LGTM, just one more organizational change and I think it will be good!

2024-05-27 18:53 UTC, Grantapher commented on ValheimPlus/Configurations/Sections/InventoryConfiguration.cs
> +        public bool autoStackAllIgnoreEquipment { get; internal set; } = false;
Sorry, forgot to comment this yesterday but this could probably use its own config section rather than piggybacking on `Inventory`.

2024-05-27 18:53 UTC, Grantapher commented on ValheimPlus/GameClasses/Inventory.cs
> +        public static bool isStacking = false;
Unused

2024-05-27 18:53 UTC, Grantapher commented on ValheimPlus/GameClasses/Inventory.cs
> +        /// Start the auto stack all loop and surpress stack feedback message
typo: suppress

2024-05-27 20:30 UTC, Bellian commented on ValheimPlus/GameClasses/Inventory.cs
> +        public static bool isStacking = false;
awww forgot..

2024-05-27 20:48 UTC, Bellian commented
changed and tested

2024-05-27 21:06 UTC, Grantapher approved these changes

2024-05-27 21:07 UTC, merged

2024-10-10 03:35 UTC, VulcanTourist commented
This feature now needs to be (self-)documented!  The description in the CFG is inadequate to explain what it does in an unambiguous fashion.  This might also be true of some other new features.  No one even seems to know of this AutoStack because the NexusMods forum is lacking even one reference to it.

2024-10-10 06:32 UTC, Grantapher commented
> Set to true to automatically perform the "Stack All" action on all chests in range.

What problem do you have with this? If you have a better description then feel free to send a pr.

2024-10-10 06:45 UTC, VulcanTourist commented
> What problem do you have with this? If you have a better description then feel free to send a pr.

I already explained one potential ambiguity above.  I don't think I can give a better single example of how it's ambiguous.

It also says "automatically" in the CFG, but again someone is presuming that users have the inherent knowledge of the developer.  Exactly what is automatic?  In the discussions here it seems like there is supposed to be an extra UI button somewhere and/or an extended keypress to activate it - meaning that it's **not** truly automatic - and neither of which are mentioned in relation to "automatic".

I tried enabling the feature tonight, and it caused nothing at all to happen with player inventory while in range, neither without intervention nor by long-pressing the interaction ([E]) key.  If it's truly expected to be fully automatic, then it's not working as intended for me.  That is aside from the documentation issue.